### ISSUE TITLE
Consolidate test functions

### ISSUE THREAD

**Issue by pulyaevskiy** [pulyaevskiy/firebase-functions-interop#13]
Too often Travis builds result in:

```
You have exceeded your deployment quota, please deploy your functions in batches by using the --only flag, and wait a few minutes before deploying again. Go to https://firebase.google.com/docs/cli/#partial_deploys to learn more.
```

Should be able to reduce number of functions to one per type (https, database, pubsub, etc).

**Comment by Cretezy** [comment]
I think the simpler version would be to request a quota increase. They are pretty generous and understanding, especially for things like this project.

**Comment by pulyaevskiy** [comment]
Just did a small clean up in https functions in #15. I also removed cleaning step from `tool/deploy.sh` as it seems redundant to me now.

Thanks for the idea about quota. Though I didn't want to enable billing in this project at this point, will save this option for the next time.
