### ISSUE TITLE
Support for Firebase Authentication Triggers

### ISSUE THREAD

**Issue by TonyDowney** [pulyaevskiy/firebase-functions-interop#16]
Support for functions.auth.user().onCreate & functions.auth.user().onDelete

Reference Docs:
https://firebase.google.com/docs/reference/functions/functions.auth.UserBuilder
https://firebase.google.com/docs/functions/auth-events

Thanks!

**Comment by pulyaevskiy** [comment]
Thanks for submitting this request.

Some notes: looks like at least `UserInfo` and `UserMetadata` can be reused from firebase_admin_interop. `UserRecord` looks similar but hides some fields (like `passwordHash`) so might be better to create separate binding.

@Cretezy just wondering if you planned to tackle this any time soon? I should have some time in a couple days to get this don, so don't want us both spend time doing the same thing.

**Comment by Cretezy** [comment]
Yeah, I can work on it tonight and tomorrow. I'll have a PR within a day hopefully!

**Comment by Cretezy** [comment]
Started https://github.com/pulyaevskiy/firebase-functions-interop/pull/17

**Comment by Cretezy** [comment]
Merged!

**Comment by pulyaevskiy** [comment]
I'm about to release a Pub version. Stay tuned!

**Comment by pulyaevskiy** [comment]
https://pub.dartlang.org/packages/firebase_functions_interop/versions/1.0.0-dev.3.0

Thanks @Cretezy !

@TonyDowney please report if you find any issues with the new version.
