### ISSUE TITLE
Firebase-functions-interop needs to use the new build system instead of transformers

### ISSUE THREAD

**Issue by efortuna** [pulyaevskiy/firebase-functions-interop#20]
Transformers are going away, so we should change this package to use the new build system:
https://github.com/dart-lang/build

From my superficial look I think we can use the [build_web_compilers](https://github.com/dart-lang/build/tree/master/build_web_compilers) process to compile to JavaScript (even though this is not a web thing).

As a small incentive...we're hoping to feature this package in my (Flutter) Google I/O presentation, assuming it can work with Dart 2!

**Comment by pulyaevskiy** [comment]
Hi Emily,

Have you tried [1.0.0-dev](https://pub.dartlang.org/packages/firebase_functions_interop/versions/1.0.0-dev.3.0) version of this package?

It implements exactly what you mentioned:

* Works with Dart 2
* Uses build_runner via [build_node_compilers](https://pub.dartlang.org/packages/build_node_compilers)
* Compiles with both DDC and Dart2JS (though DDC output doesn't work with this package specifically, only dart2js output can be uploaded with the Firebase tool)
* Implements many more triggers including Firestore, Auth, etc.

Let me know if anything is not working for you, I'll try to help.

P.S.: Would be cool to see it featured in your talk! :)

**Comment by efortuna** [comment]
oh geez, you're right! Sorry about that. I was looking at the wrong version because apparently Google decided to show that one first when I searched. https://pub.dartlang.org/packages/firebase_functions_interop/versions/0.0.4%2B1 
Sorry for the noise!

**Comment by efortuna** [comment]
(ps. thanks for writing this package!)

**Comment by pulyaevskiy** [comment]
No worries, thanks for trying it out! As I mentioned, let me know in case you'll find any issues.
