### ISSUE TITLE
App calls Support

### ISSUE THREAD

**Issue by grundid** [pulyaevskiy/firebase-functions-interop#26]
Do you plan on adding callable functions support to this library?

https://firebase.google.com/docs/functions/callable

**Comment by pulyaevskiy** [comment]
Oh, I somehow missed they added this. Definitely! Should be a simple update.

Thanks for reporting, should have this added later today if my plans don’t change.

**Comment by pulyaevskiy** [comment]
I've published a new version which exposes `onCall` trigger. Did a basic test which seemed to work.
https://pub.dartlang.org/packages/firebase_functions_interop/versions/1.0.0-dev.5.0

Closing this issue as resolved. Feel free to submit new issue in case you find any bugs.
