### ISSUE TITLE
Unable to send/receive binary data (e.g. Buffer, Uint8List) in HTTPS function

### ISSUE THREAD

**Issue by paulreimer** [pulyaevskiy/firebase-functions-interop#29]
This works with `node_interop` and Google Cloud Function (binary data is returned in the response): 
```
Uint8List responseBytes = ...;
res
  ..statusCode = 200 // OK
  ..write(Buffer.from(responseBytes))
  ..end();
```

But with `firebase-functions-interop` it returns the toString representation of a `List<int>` of the binary data:
```
Uint8List responseBytes = ...;
request.response
  ..statusCode = 200 // OK
  ..write(Buffer.from(responseBytes))
  ..close();
```

Produces the output:
```
[24, 0, 0, 0, 65, 67, 77, 46, 16,...]
```

**Comment by pulyaevskiy** [comment]
The ‘write’ method is supposed to only write string values. Everything that is not a ‘String’, gets converted with ‘toString()’ call. This contract comes from the Dart’s IOSink class, actually, node_io simply tries to follow it. Docs: https://api.dartlang.org/dev/2.0.0-dev.63.0/dart-io/IOSink/write.html

To add byte data there is ‘add’ method.

Hope this helps.

**Comment by pulyaevskiy** [comment]
Oh, the first example shouldn’t work either. This is strange since firebase functions use the same node_io implementation.

**Comment by paulreimer** [comment]
Well, oddly the first example does work! Maybe the `Buffer.from(...)` is affecting things? But using `add` also works in both cases (so it does resolve this issue for me!).

In fact I no longer need the `package:node_interop:buffer.dart` dependency and I can `add` my Uint8List bytes directly.

Thanks so much for the help!

**Comment by pulyaevskiy** [comment]
Glad it works for you now.

Wondering if you can provide a more complete version of the first example? Would be nice to figure out what's going on there.

**Comment by paulreimer** [comment]
Coming back to this now, since I am back to using `node_interop` for instead of `firebase-functions-interop`. Turns out, I think I was just getting lucky with the first approach using `res.write(Buffer.from(responseBytes))` where res is a `ServerResponse` type.

I think I would like `res.add(responseBytes)`, but I get the following error:
```
undefined_method: The method 'add' isn't defined for the class 'ServerResponse'
```

If this is issue is better off moved `node_interop` I can do that (since using `add` with the firebase interop `request.response.add` seems to be working great!).

**Comment by Dzivo** [comment]
This still doesnt work from JS / TS i just get 200 OK {} empty json response what ever i return from the server. Tried all of the headers manually added as well
