### ISSUE TITLE
FirestoreEvent in Readme.md does not exist

### ISSUE THREAD

**Issue by gazialankus** [pulyaevskiy/firebase-functions-interop#32]
The Firestore example in Readme.md has the type [FirestoreEvent](https://github.com/pulyaevskiy/firebase-functions-interop/blob/ae2670df12905b9f416da6b985ce0b697bbbe526/README.md#L256) as a function parameter. This type does not exist [anywhere else](https://github.com/pulyaevskiy/firebase-functions-interop/search?q=FirestoreEvent&unscoped_q=FirestoreEvent). The example code has [another signature](https://github.com/pulyaevskiy/firebase-functions-interop/blob/master/example/main.dart#L42) for this function that I verified to work fine. The one from Readme.md is probably left over from an old version, that and the docs in pub.dartlang.org should be updated.

**Comment by pulyaevskiy** [comment]
Sorry for the delay here. I've updated readme with correct examples. Thanks for noticing!
