### ISSUE TITLE
Running a HTTP client over TLS 1.2 from a cloud function

### ISSUE THREAD

**Issue by kostaa** [pulyaevskiy/firebase-functions-interop#37]
I am implementing the OAuth 2.0 'authorization code grant' flavour with an option of using the TLS 1.2 protocol. I am using `dart.io` for the front channel (with the SecurityContext for the TLS option) and a cloud function for the back channel (callback). 

During the token exchange phase the back channel starts a http client to call the authorization server to get the token. So the client needs to run over the TLS when this is required.

I had a look into the `package:node_http/node_http.dart` but I could not see a way to start a http client with the certificate/key. As far as I know the underlying node.js supports SSL/TLS. Would it be possible to expose this in the interop Dart layer?

**Comment by pulyaevskiy** [comment]
> Would it be possible to expose this in the interop Dart layer?

Yes, definitely. Should be fairly quick thing to do. Will have an update here later today.

**Comment by kostaa** [comment]
Wow that was quick! I will close this now and will test it at some point within the next two weeks. If I find any issues I will come back to you. 

Many thanks you have been very helpful!
