### ISSUE TITLE
Add support for locations/regions

### ISSUE THREAD

**Issue by grundid** [pulyaevskiy/firebase-functions-interop#44]
Firebase functions can have different locations. Could you please add support for that?

https://firebase.google.com/docs/functions/locations

**Comment by pulyaevskiy** [comment]
Thanks for reporting. Definitely, will work on this during the week. Might even get it in later today.

**Comment by pulyaevskiy** [comment]
Just published `1.0.0` (stable) which adds `region` and `runWith` methods to functions.

Note that it's also a breaking change release. See UPGRADING.md or CHANGELOG.md for more details.

Closing as resolved.
