### ISSUE TITLE
onCreate is calling native onWrite

### ISSUE THREAD

**Issue by tomas259** [pulyaevskiy/firebase-functions-interop#5]
in file firebase_functions_interop.dart ln 168

  js.CloudFunction onCreate<T>(FutureOr<Null> handler(DatabaseEvent<T> event),
      [Serializer<T> serializer]) {
    dynamic wrapper(js.Event event) {
      return _handleEvent<T>(event, handler, serializer);
    }

    return nativeInstance.onWrite(allowInterop(wrapper));
  }
----------------------------

shold be 
    return nativeInstance.onCreate(allowInterop(wrapper));

same for onDelete and onUpdate

**Comment by pulyaevskiy** [comment]
Thanks for reporting!

This should be fixed now and available in 0.1.0-beta.2
https://pub.dartlang.org/packages/firebase_functions_interop/versions/0.1.0-beta.2

Feel free to file a new issue if something is not working for you still.
