### ISSUE TITLE
Fails to compile with node_io 1.0.0

### ISSUE THREAD

**Issue by alextekartik** [pulyaevskiy/firebase-functions-interop#52]
Thanks again for your package. The latest change you made to node_io (1.0.0) seems to break this package.
Tested on sdk 2.3.0-dev.0.0 Ubuntu.

The workaround for me for now is to add the following constraint:

```yaml
  node_io: 1.0.0-dev.10.0
```

**Comment by pulyaevskiy** [comment]
Ouch, thanks for pointing it out! Will investigate.

**Comment by pulyaevskiy** [comment]
There is now `node_io: 1.0.1` which fixes this issue. I also updated `firebase_functions_interop: 1.0.1` with latest dependencies.

Thanks!
